### ISSUE TITLE
Installation not working on my C3

### ISSUE THREAD

**Issue by DerGue69** [openpilotkr/openpilot#15]
The installation seem to run fine, downloads and progress bar finish.
Then comes the reboot with the scroll to accept...when i try to scroll, the C3 is not reacting. 
And after 2 secodns the comma.ai logo appears forever.

**Comment by DerGue69** [comment]
When I reboot - same thing. Scroll to accept appears. 
When I try to scroll, nothing happens. Thenn the Comma Logo.

**Comment by haram-KONA** [comment]
Perhaps.....
 OPKR doesn't support Comma.ai C3 yet.
Only C2 will be supported yet.

**Comment by multikyd** [comment]
no test bed for comma3 for now. think still enough with comma2 or eon. But I agree comma3 is better if you are able to have it.
