### ISSUE TITLE
Discord invite in readme is dead

### ISSUE THREAD

**Issue by nelsonjchen** [openpilotkr/openpilot#26]

**Comment by TiphTech** [comment]
Discord link is in readme:

Join The OPKR Server

https://discord.gg/6H9k4B5a

**Comment by nelsonjchen** [comment]
@TiphTech Am I banned from that Discord? I get an invalid invite message.

**Comment by TiphTech** [comment]
Ok so try this link plz: https://discord.gg/VgvBf6Ea

**Comment by nelsonjchen** [comment]
@TiphTech Awesome, looks like that works. 

That said, whatever invite link eventually goes into the readme, please make sure to generate it with no expiration date. The UI defaults to 7 days.

**Comment by TiphTech** [comment]
Ok perfect, that's noted

**Comment by TiphTech** [comment]
https://discord.gg/pppFp2pVW3
new link unlimited
Thanks, you can close this issue please

**Comment by nelsonjchen** [comment]
@TiphTech this will auto-close when PR #27 is merged.

**Comment by nelsonjchen** [comment]
Pr was merged in another way.
