### ISSUE TITLE
LTE signal bars not updated

### ISSUE THREAD

**Issue by TiphTech** [openpilotkr/openpilot#5]
Hi, issue with reception bars (mobile network) we can see the type of network (LTE for example) but the bars are not updated according to the strength of the signal (on my C2, it remains stuck on the strength of the previous signal -> wifi & I can see my IP always on screen)

Batteryless option selected but we can see the "battery" status next to LTE

Thx!

(issue encountered even after a clean install)

![IMG_4429](https://user-images.githubusercontent.com/77073571/152520762-b802c22d-c483-4b40-9f3c-1a723bef8419.jpeg)

Satellites issue: https://youtu.be/sntw0B3Bvsc

We can see satellites and online mode car OFF, when put the car ON satellites was disappears and offline mode

**Comment by multikyd** [comment]
thx for raising an issue. i'm performing some test with different cases. but could not find any root causes. still on testing and trying to figure it out. use lte router or wifi as workaround until resolved.

**Comment by TiphTech** [comment]
Ok thx, yes that's what i'm doing in the meantime

**Comment by multikyd** [comment]
i've modified some code. pls do a test whether that issue gone.

**Comment by TiphTech** [comment]
Perfect! it was fixed :) thank you very much
![image](https://user-images.githubusercontent.com/77073571/153361806-0211c4be-36fb-4886-ad81-8edeb8509691.jpeg)

**Comment by TiphTech** [comment]
Fixed on OPKR_test branch, issues already present on main branch
