### ISSUE TITLE
GPS / Satellites issue after restart car (with C2)

### ISSUE THREAD

**Issue by TiphTech** [openpilotkr/openpilot#6]
Hello 👋  
Already have GPS / Satellites issue when I put OFF then ON my car, satellites was coming after a long time, sometimes one reboot is necessary
Device: Comma Two
Branch: test (same issue on main)
Comma power option selected

More understandable with picture:
![GPS issue](https://user-images.githubusercontent.com/77073571/155493873-4a87c351-aa6f-4294-94dd-36f52b92b461.jpg)

Thank you 🙂

**Comment by multikyd** [comment]
Seems like the issue has gone. D.Fyffe confirmed that.

**Comment by TiphTech** [comment]
Yes! (sorry)
I confirm, all works perfectly fine now, thank you very much for your amazing work! :)
