### ISSUE TITLE
recording time is just 3 minites

### ISSUE THREAD

**Issue by chocomilks** [openpilotkr/openpilot#9]
(질문 수정: 죄송합니다. 제가 이해를 잘 못하고 있었네요.)
자동녹화시 파일이 1개만 만들어지다보니 3분 녹화만 되고 있습니다.
20분 주행을 하면 3분짜리 7개 파일이 만들어져야 하는데, 1개만 만들어져있습니다.

**Comment by multikyd** [comment]
already discussed about this in the cafe, https://cafe.naver.com/carhightech/617
